add_newline = false
# A minimal left prompt
format = """$directory$character"""
palette = "catppuccin_mocha"
# move the rest of the prompt to the right
right_format = """
$git_branch\
$git_status\
$lua\
$python\
$nodejs\
$golang\
$package\
$aws\
$docker_context\
$cmd_duration\
"""

command_timeout = 1000

[cmd_duration]
format = ' took [$duration](bold yellow)'

[git_branch]
symbol = ' '
format =  '[$symbol$branch(:$remote_name)]($style) '

[git_status]
format = '([$all_status$ahead_behind]($style) )'

[lua]
format = '[$symbol($version)]($style)'
symbol = ' '

[nodejs]
symbol = ' '
format = '[$symbol$version]($style)'

[python]
symbol = ' '
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
pyenv_version_name = true
pyenv_prefix = ''

[golang]
symbol = ' '
style = 'bold cyan'
format = '[$symbol($version )]($style)'

[package]
symbol = ' 󰏗 '
format = '[$symbol($version)]($style)'

[aws]
symbol = ' '
style = 'bold blue'
format = '[$symbol($profile )(\[$duration\] )]($style)'

[docker_context]
symbol = '  '
format = '[$symbol]($style)'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
